### ISSUE TITLE
Python errors relating to scandir levels

### ISSUE THREAD

**Issue by mxmilkiib** [kewlfft/pkgwap#1]
Without a level arg;
```
./pkgwap ~/pkgs 
Package name                       Local              AUR            Upstream            Status
Traceback (most recent call last):
  File "./pkgwap", line 594, in <module>
    scandir(args.DIR, args.level)
  File "./pkgwap", line 583, in scandir
    pkgm.pkglist.append(PKGBUILD(os.path.join(root, 'PKGBUILD')))
  File "./pkgwap", line 145, in __init__
    self._parse(fileobj)
  File "./pkgwap", line 191, in _parse
    self._handle_assign(token)
  File "./pkgwap", line 153, in _handle_assign
    if value[0] == '(' and value[-1] == ')':
IndexError: string index out of range
```

and 

With a level arg;
```
./pkgwap -l 1 ~/pkgs/
Package name                       Local              AUR            Upstream            Status
Traceback (most recent call last):
  File "./pkgwap", line 594, in <module>
    scandir(args.DIR, args.level)
  File "./pkgwap", line 580, in scandir
    for (root, dirs, files) in walklevel(path, level):
  File "./pkgwap", line 569, in walklevel
    if num_sep + level <= num_sep_this:
TypeError: unsupported operand type(s) for +: 'int' and 'list'
```

**Comment by kewlfft** [comment]
Thanks Milk, a PR would be welcome if you think it is necessary.

**Comment by mxmilkiib** [comment]
Might it be the case that there are other required arguments which I have missed that are causing this error, or a potential problem with untoward files in a scanned subdirectory, or does the script just plain not work atm?

I don't have the time, knowledge of Python or energy to focus on resolving this. Not that I have any expectation that you will continue to develop it, I just thought you might appreciate a report of the problem :)

**Comment by kewlfft** [comment]
Thanks for reporting it this is appreciated, I use this tool on a daily basis and will continue to develop and support it.

**Comment by mxmilkiib** [comment]
Hmm, so it works for you? Any possible thoughts as to why it isn't for me?

**Comment by kewlfft** [comment]
I don't know
